IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'medios_pago' AND COLUMN_NAME = 'rechazado')
    ALTER TABLE dbo.medios_pago ADD rechazado BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'medios_pago' AND COLUMN_NAME = 'notificado_rechazo')
    ALTER TABLE dbo.medios_pago ADD notificado_rechazo BIT NOT NULL DEFAULT 0;
